import { Hono } from 'hono';
import { requireAuth } from '../lib/auth';
import { getDB, generateId, now } from '../lib/db';

const github = new Hono();

// POST /api/github/export — export project files to a GitHub repo
github.post('/export', async (c) => {
  const auth = await requireAuth(c);
  if (!auth) return c.json({ error: 'Unauthorized' }, 401);

  const body = await c.req.json();
  const { projectId, repoName, description, files, isPrivate = false, githubToken } = body;

  if (!projectId || !repoName || !files || !githubToken) {
    return c.json({ error: 'projectId, repoName, files, and githubToken are required' }, 400);
  }

  const blink = getDB(c.env as any);

  // Verify project ownership
  const project = await blink.db.projects.get(projectId);
  if (!project || (project as any).userId !== auth.userId) {
    return c.json({ error: 'Project not found' }, 404);
  }

  const ghHeaders = {
    'Authorization': `token ${githubToken}`,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // Get GitHub user
  const userRes = await fetch('https://api.github.com/user', { headers: ghHeaders });
  if (!userRes.ok) return c.json({ error: 'Invalid GitHub token' }, 401);
  const ghUser = await userRes.json() as any;
  const repoOwner = ghUser.login;

  // Check if repo exists
  const repoCheckRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}`, { headers: ghHeaders });
  let repo: any;

  if (repoCheckRes.status === 404) {
    // Create repo
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: ghHeaders,
      body: JSON.stringify({
        name: repoName,
        description: description || `Generated by m7a — ${(project as any).name || 'Project'}`,
        private: isPrivate,
        auto_init: false,
      }),
    });
    if (!createRes.ok) {
      const err = await createRes.json() as any;
      return c.json({ error: err.message || 'Failed to create repo' }, 400);
    }
    repo = await createRes.json();
  } else {
    repo = await repoCheckRes.json();
  }

  // Get or create default branch
  const defaultBranch = repo.default_branch || 'main';
  
  // Get latest commit SHA for tree base
  let treeSha: string | null = null;
  let commitSha: string | null = null;
  
  const branchRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/ref/heads/${defaultBranch}`, { headers: ghHeaders });
  if (branchRes.ok) {
    const branchData = await branchRes.json() as any;
    commitSha = branchData.object?.sha;
    if (commitSha) {
      const commitRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/commits/${commitSha}`, { headers: ghHeaders });
      if (commitRes.ok) {
        const commitData = await commitRes.json() as any;
        treeSha = commitData.tree?.sha;
      }
    }
  }

  // Create blobs for each file
  const treeItems: any[] = [];
  for (const [path, content] of Object.entries(files as Record<string, string>)) {
    const blobRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/blobs`, {
      method: 'POST',
      headers: ghHeaders,
      body: JSON.stringify({
        content: btoa(unescape(encodeURIComponent(content as string))),
        encoding: 'base64',
      }),
    });
    if (!blobRes.ok) continue;
    const blob = await blobRes.json() as any;
    treeItems.push({
      path,
      mode: '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  // Create tree
  const treeBody: any = { tree: treeItems };
  if (treeSha) treeBody.base_tree = treeSha;
  
  const treeRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/trees`, {
    method: 'POST',
    headers: ghHeaders,
    body: JSON.stringify(treeBody),
  });
  if (!treeRes.ok) return c.json({ error: 'Failed to create git tree' }, 500);
  const tree = await treeRes.json() as any;

  // Create commit
  const commitBody: any = {
    message: '🚀 Generated by m7a',
    tree: tree.sha,
  };
  if (commitSha) commitBody.parents = [commitSha];

  const newCommitRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/commits`, {
    method: 'POST',
    headers: ghHeaders,
    body: JSON.stringify(commitBody),
  });
  if (!newCommitRes.ok) return c.json({ error: 'Failed to create commit' }, 500);
  const newCommit = await newCommitRes.json() as any;

  // Update branch ref (or create it)
  const refUrl = `https://api.github.com/repos/${repoOwner}/${repoName}/git/refs/heads/${defaultBranch}`;
  const refCheckRes = await fetch(refUrl, { headers: ghHeaders });
  
  if (refCheckRes.ok) {
    // Update existing ref
    await fetch(refUrl, {
      method: 'PATCH',
      headers: ghHeaders,
      body: JSON.stringify({ sha: newCommit.sha, force: false }),
    });
  } else {
    // Create new ref
    await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/refs`, {
      method: 'POST',
      headers: ghHeaders,
      body: JSON.stringify({ ref: `refs/heads/${defaultBranch}`, sha: newCommit.sha }),
    });
  }

  // Save integration to DB
  const existing = await blink.db.githubIntegrations.list({
    where: { projectId, userId: auth.userId },
    limit: 1,
  });

  const integrationData = {
    projectId,
    userId: auth.userId,
    repoOwner,
    repoName,
    repoFullName: repo.full_name,
    repoUrl: repo.html_url,
    defaultBranch,
    githubAccessToken: githubToken,
    lastPushedAt: now(),
    updatedAt: now(),
  };

  let integration: any;
  if (existing.length > 0) {
    await blink.db.githubIntegrations.update((existing[0] as any).id, integrationData);
    integration = { ...(existing[0] as any), ...integrationData };
  } else {
    const id = generateId('ghint');
    integration = await blink.db.githubIntegrations.create({
      id,
      ...integrationData,
      createdAt: now(),
    });
  }

  // Save version record
  await blink.db.projectVersions.create({
    id: generateId('ver'),
    projectId,
    userId: auth.userId,
    versionNumber: 1,
    description: `Exported to GitHub: ${repo.full_name}`,
    githubCommitSha: newCommit.sha,
    createdAt: now(),
  });

  return c.json({
    ok: true,
    repo: {
      fullName: repo.full_name,
      url: repo.html_url,
      defaultBranch,
      commitSha: newCommit.sha,
    },
    integration,
  });
});

// GET /api/github/integration/:projectId — get GitHub integration for a project
github.get('/integration/:projectId', async (c) => {
  const auth = await requireAuth(c);
  if (!auth) return c.json({ error: 'Unauthorized' }, 401);

  const projectId = c.req.param('projectId');
  const blink = getDB(c.env as any);

  const rows = await blink.db.githubIntegrations.list({
    where: { projectId, userId: auth.userId },
    limit: 1,
  });

  if (rows.length === 0) return c.json({ integration: null });

  // Don't expose the token
  const integration = { ...(rows[0] as any) };
  delete integration.githubAccessToken;

  return c.json({ integration });
});

// POST /api/github/push — push updated files to existing repo
github.post('/push', async (c) => {
  const auth = await requireAuth(c);
  if (!auth) return c.json({ error: 'Unauthorized' }, 401);

  const body = await c.req.json();
  const { projectId, files, message = '🔄 Updated by m7a', githubToken } = body;

  if (!projectId || !files || !githubToken) {
    return c.json({ error: 'projectId, files, and githubToken are required' }, 400);
  }

  const blink = getDB(c.env as any);

  const integrations = await blink.db.githubIntegrations.list({
    where: { projectId, userId: auth.userId },
    limit: 1,
  });

  if (integrations.length === 0) {
    return c.json({ error: 'No GitHub integration found. Export first.' }, 404);
  }

  const integration = integrations[0] as any;
  const { repoOwner, repoName, defaultBranch } = integration;

  const ghHeaders = {
    'Authorization': `token ${githubToken}`,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // Get latest commit
  const branchRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/ref/heads/${defaultBranch}`, { headers: ghHeaders });
  if (!branchRes.ok) return c.json({ error: 'Failed to get branch info' }, 500);
  const branchData = await branchRes.json() as any;
  const latestSha = branchData.object?.sha;

  const commitRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/commits/${latestSha}`, { headers: ghHeaders });
  const commitData = await commitRes.json() as any;
  const treeSha = commitData.tree?.sha;

  // Create blobs
  const treeItems: any[] = [];
  for (const [path, content] of Object.entries(files as Record<string, string>)) {
    const blobRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/blobs`, {
      method: 'POST',
      headers: ghHeaders,
      body: JSON.stringify({ content: btoa(unescape(encodeURIComponent(content as string))), encoding: 'base64' }),
    });
    if (!blobRes.ok) continue;
    const blob = await blobRes.json() as any;
    treeItems.push({ path, mode: '100644', type: 'blob', sha: blob.sha });
  }

  const treeRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/trees`, {
    method: 'POST',
    headers: ghHeaders,
    body: JSON.stringify({ tree: treeItems, base_tree: treeSha }),
  });
  const tree = await treeRes.json() as any;

  const newCommitRes = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/commits`, {
    method: 'POST',
    headers: ghHeaders,
    body: JSON.stringify({ message, tree: tree.sha, parents: [latestSha] }),
  });
  const newCommit = await newCommitRes.json() as any;

  await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}/git/refs/heads/${defaultBranch}`, {
    method: 'PATCH',
    headers: ghHeaders,
    body: JSON.stringify({ sha: newCommit.sha }),
  });

  await blink.db.githubIntegrations.update(integration.id, {
    lastPushedAt: now(),
    updatedAt: now(),
  });

  return c.json({ ok: true, commitSha: newCommit.sha, repoUrl: `https://github.com/${repoOwner}/${repoName}` });
});

export default github;
